enum BottomSheetTypes {
  newCatalog,
  pickProductVariant,
  catalog,
  selectSize,
  signOut,
  authSignOut,
  deleteProductsInCatalog,
  incompleteProfile,
  verifyPhoneBack,
  share,
  reportVideo,
  reportVideoConfirm,
  reportVideoThanks,
  reportVideoBlockBrand,
}
