name: flutter_estrellas
description: "Estrellas"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.23+232

environment:
  sdk: ^3.5.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_remote_config: ^5.1.5
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  json_serializable: ^6.9.0
  package_info_plus: ^8.1.1
  rxdart: ^0.28.0
  uuid: ^4.5.1
  freezed_annotation: ^2.4.4
  lottie: ^3.1.3
  adaptive_dialog: ^2.2.1
  macos_window_utils: ^1.6.1
  universal_platform: ^1.1.0
  cupertino_modal_sheet: ^1.1.0
  flutter_svg: ^2.0.14
  get: ^4.6.6
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  reactive_forms: ^17.0.1
  reactive_phone_form_field: ^4.0.0
  shimmer: ^3.0.0
  video_compress: ^3.1.3
  modal_bottom_sheet: ^3.0.0
  dotted_line: ^3.2.3
  url_launcher: ^6.3.1
  flutter_sticky_header: ^0.7.0
  easy_image_viewer: ^1.5.1
  flutter_native_splash: ^2.4.3
  flutter_staggered_grid_view: ^0.7.0
  text_transformation_animation: ^0.1.4
  flutter_slidable: ^3.1.1
  pinput: ^5.0.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/images/
    - assets/fonts/
    - assets/lotties/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: EstrellasIcons
      fonts:
        - asset: assets/fonts/icons/estrellas_font.otf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
