part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const SPLASH = _Paths.SPLASH;
  static const REGISTER = _Paths.REGISTER;
  static const REGISTER_BASIC_DATA = _Paths.REGISTER_BASIC_DATA;
  static const WELCOME = _Paths.WELCOME;
  static const PRODUCT = _Paths.PRODUCT;
  static const CART = _Paths.CART;
  static const ADDRESS = _Paths.ADDRESS;
  static const NEW_ADDRESS = _Paths.NEW_ADDRESS;
  static const SELECT_DEPARTMENT = _Paths.SELECT_DEPARTMENT;
  static const SELECT_CITY = _Paths.SELECT_CITY;
  static const SELECT_PAYMENT = _Paths.SELECT_PAYMENT;
  static const ORDER_SUCCESS = _Paths.ORDER_SUCCESS;
  static const STORE = _Paths.STORE;
  static const WALLET = _Paths.WALLET;
  static const SEARCH = _Paths.SEARCH;
  static const ACCOUNT = _Paths.ACCOUNT;
  static const PRODUCT_DETAILS = _Paths.PRODUCT_DETAILS;
  static const FAVORITES = _Paths.FAVORITES;
  static const ORDERS = _Paths.ORDERS;
  static const BANK_ACCOUNTS = _Paths.BANK_ACCOUNTS;
  static const ABOUT = _Paths.ABOUT;
  static const PROFILE = _Paths.PROFILE;
  static const VIDEO_LIST = _Paths.VIDEO_LIST;
  static const LOGIN_START = _Paths.LOGIN_START;
  static const NEW_LOGIN = _Paths.NEW_LOGIN;
  static const NEW_REGISTER = _Paths.NEW_REGISTER;
  static const EMAIL_VERIFICATION = _Paths.EMAIL_VERIFICATION;
  static const ORDER_ERROR = _Paths.ORDER_ERROR;
  static const ORDERS_LIST = _Paths.ORDERS_LIST;
  static const ORDER_DETAILS = _Paths.ORDER_DETAILS;
  static const CATALOG_DETAILS = _Paths.CATALOG_DETAILS;
  static const PHONE_VERIFICATION = _Paths.PHONE_VERIFICATION;
  static const VIDEO_DETAILS = _Paths.VIDEO_DETAILS;
  static const NOTIFICATIONS_LIST = _Paths.NOTIFICATIONS_LIST;
  static const NEW_BANK_ACCOUNT = _Paths.NEW_BANK_ACCOUNT;
  static const NEW_BANK_CONFIRMATION = _Paths.NEW_BANK_CONFIRMATION;
  static const SOCIAL_MEDIA_SHARE = _Paths.SOCIAL_MEDIA_SHARE;
  static const CART_UNIQUE_PRODUCT = _Paths.CART_UNIQUE_PRODUCT;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/';
  static const LOGIN = '/login';
  static const SPLASH = '/splash';
  static const REGISTER = '/register';
  static const REGISTER_BASIC_DATA = '/register-basic-data';
  static const WELCOME = '/welcome';
  static const PRODUCT = '/product';
  static const CART = '/cart';
  static const ADDRESS = '/address';
  static const NEW_ADDRESS = '/new-address';
  static const SELECT_DEPARTMENT = '/select-department';
  static const SELECT_CITY = '/select-city';
  static const SELECT_PAYMENT = '/select-payment';
  static const ORDER_SUCCESS = '/order-success';
  static const STORE = '/store';
  static const WALLET = '/wallet';
  static const SEARCH = '/search';
  static const ACCOUNT = '/account';
  static const PRODUCT_DETAILS = '/product-details';
  static const FAVORITES = '/favorites';
  static const ORDERS = '/orders';
  static const BANK_ACCOUNTS = '/bank-accounts';
  static const ABOUT = '/about';
  static const PROFILE = '/profile';
  static const VIDEO_LIST = '/video-list';
  static const LOGIN_START = '/login-start';
  static const NEW_LOGIN = '/new-login';
  static const NEW_REGISTER = '/new-register';
  static const EMAIL_VERIFICATION = '/email-verification';
  static const ORDER_ERROR = '/order-error';
  static const ORDERS_LIST = '/orders-list';
  static const ORDER_DETAILS = '/order-details';
  static const CATALOG_DETAILS = '/catalog-details';
  static const PHONE_VERIFICATION = '/phone-verification';
  static const VIDEO_DETAILS = '/video-details';
  static const NOTIFICATIONS_LIST = '/notifications-list';
  static const NEW_BANK_ACCOUNT = '/new-bank-account';
  static const NEW_BANK_CONFIRMATION = '/new-bank-confirmation';
  static const SOCIAL_MEDIA_SHARE = '/social-media-share';
  static const CART_UNIQUE_PRODUCT = '/cart-unique-product';
  static const FORGOT_PASSWORD = '/forgot-password';
}
